ListsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ListsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: boardId
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: boardIdIndex
        KeySchema:
          - AttributeName: boardId
            KeyType: HASH
        Projection:
          ProjectionType: ALL