BoardsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: BoardsTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: visibility
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH

    GlobalSecondaryIndexes:
      - IndexName: visibilityIndex
        KeySchema:
          - AttributeName: visibility
            KeyType: HASH
        Projection:
          ProjectionType: ALL